### ISSUE TITLE
Passing nunjucks environment into the options

### ISSUE THREAD

**Issue by Poselsky** [ogonkov/nunjucks-loader#106]
**Is your feature request related to a problem? Please describe.**

I have two projects (server and client) and want to create shared templates between those projects. So sharing same nunjucks environment object and it's globals would be a pretty neat solution. But right now, I need to create function wrappers to overcome  globals functionality obstacle.
[Per this global-fn.js example.](https://github.com/ogonkov/nunjucks-loader/blob/master/README.md#globals) 

**Describe the solution you'd like**

It would be nice to have a way passing an existing nunjucks environment variable into the options.globals (or add new property into the options). 

**Additional context**

If this feature will be accepted, I can try to create PR.

**Comment by ogonkov** [comment]
I'm not quite follow what problem did you face. Can you give a small example of the problem with globals functionality?

**Comment by Poselsky** [comment]
Sorry for not describing problem more precisely. Here are examples:

*Creating example class*

```javascript
class Example{
  // fancy code here
}
```

*Declaring environment*:

```javascript
const env = nunjucks.configure(sourceDirectory, someOtherConfigs )

//I can pass object like this instead of exporting each function of the class
env.addGlobal('Example', new Example());
```
By creating nunjucks environment, I can share this environment with webpack and also with server side application.

*webpack.config.json*

```javascript

module.exports = {
  module:{
     {
       test: /.(html|njk|nunjucks)$/,
       exclude: /node_modules/,
       use: [
         {
           loader: 'simple-nunjucks-loader',
           options: {
             //pass env variable here
           },
        ]
    },

  }
}
```

**Comment by ogonkov** [comment]
What the difference from current solution with `globals` param?

```js
module.exports = {
  module:{
     {
       test: /.(html|njk|nunjucks)$/,
       exclude: /node_modules/,
       use: [
         {
           loader: 'simple-nunjucks-loader',
           options: {
             globals: {
               Example: 'path/to/example.js'
             }
           },
        ]
    },

  }
}
```

**Comment by Poselsky** [comment]
![2021-01-08_15-09](https://user-images.githubusercontent.com/45047700/104024565-9712db00-51c3-11eb-94d5-196db946b371.png)
When using globals, class methods are called within the brackets. (addSrc is a method)

> How did you do that?
By using almost the same environment configuration, I've only changed the paths. (Sharing is a bad word, should've said, almost identical configuration)

**Comment by ogonkov** [comment]
How is shared environment will help here?

**Comment by Poselsky** [comment]
Examples:

*Configure env based on source directory*
```javascript
//For webpack.config.js its __dirname + src
//For nodejs its __dirname + dist

const createNunjucksEnv = (sourceDirectory) => {
  const env = nunjucks.configure([sourceDirectory, path.join(sourceDirectory, 'entries')], nunjucksConf)
  env.addGlobal('Example', new Example());
  //add other fancy stuff

  return env;
}
```

*Node.js*
```javascript
const nunjucksEnv = createNunjucksEnv(path.join(__dirname, 'dist'));

app.get('/somepath', (req, res) => {
  const templatePath = 'path to template'
  const renderedTemplate = nunjucksEnv.render(templatePath, { /*some object values which nunjucks should render*/});
  //send rendered template to client
  res.send(renderedTemplate); 
})
```

*webpack.config.js*
```javascript

module.exports = () =>  {
  const nunjucksEnv = createNunjucksEnv(path.join(__dirname, 'src'));
  
  return ({
    // webpack config object  
  })
}
```

I can create nunjucks environment in one place, instead of defining it in the webpack and also in the node js app.

**Comment by ogonkov** [comment]
If you want to render same templates with same environment, that loader create, you can just pass precompiled templates to your express app. I think you can try to do something like this:

**express.webpack.config.js**

```js
const path = require('path');

const merge = require('webpack-merge');

const config = require('./webpack.config.js');


const templatePath = 'path to template'

module.exports = merge(config, {
  entry: {
    [path.basename(templatePath)]: templatePath
  }
})
```

This will create a bunch of precompiled templates, that you can invoke in Express with required context.

```js
const templatePath = 'path to template'

const template = require(`${templatePath}.js`);

app.get('/somepath', (req, res) => {
  const renderedTemplate = template(/* template context could be passed here */);
  //send rendered template to client
  res.send(renderedTemplate);
})
```

---

Even further webpack dev server is technically an Express middleware, so i think it could be integrated on that level with your webpack config.
