### ISSUE TITLE
static seems to do not work in macro caller function

### ISSUE THREAD

**Issue by riw** [ogonkov/nunjucks-loader#109]
**Environment**
Node version: 14.16.0
simple-nunjucks-loader version: 3.1.0
webpack version: 5.26.3

**Describe the bug**
example:
```
{% macro wrap() %}
  <div>{{ caller() }}</div>
{% endmacro %}

{% call wrap() %}
  <img src="{% static 'assets/img/test.png' %}">
{% endcall %}
```
**Expected behavior**
```
<div><img src="assets/img/test.png"></div>
```
and process png

**Additional context**
TypeError: Cannot read property 'typename' of null
it is working correctly if the image is outside of the macro or if the macro doesn't contain any static

**Comment by ogonkov** [comment]
Looks like #94
