### ISSUE TITLE
Error: Template "_layout.njk" not found

### ISSUE THREAD

**Issue by eduardfossas** [ogonkov/nunjucks-loader#110]
Hello, I am on a new computer and I tried both projects that are using your module and the template cannot find the layouts or macros that I am importing it like this in case of a layout:
{% extends "_main.njk" %}

This is the error that I get:
Error: Template "_layout.njk" not found

Am I missing something?

Thanks in advance

**Comment by ogonkov** [comment]
Can you make a simple repo to reproduce error?

**Comment by eduardfossas** [comment]
Hello, do not worry about it. For some reason the node version was giving me an error. It is strange because I was using 12. Also, maybe it is a good idea to add in the documentation of the repo that you need to declare each folder inside the searchPaths.

Warm regards

**Comment by ogonkov** [comment]
You don't need to declare only your "root" folders in `searchPath` -- one that used to search files

**Comment by eduardfossas** [comment]
@ogonkov Actuall I needed to do it on my webpack 5 setup
