### ISSUE TITLE
Error while working with npm workspaces

### ISSUE THREAD

**Issue by baticodes** [ogonkov/nunjucks-loader#123]
**Environment**
Node version: 14.17.6
simple-nunjucks-loader version: 3.2.0
webpack version: 5

Using npm 7 with a workspace setup like this one:
```
+-- package.json
`-- storybook
   `-- package.json
`-- packages
   +-- ds-core
   |   `-- package.json
```

- I have all my .njk files inside ds-core package.
- ds-core package is a dependency of storybook (among other projects)

**Describe the bug**
My simple-nunjucks-loader config through errors when trying to find relative folders that are outside the current folder, so storybook doesn't even start. Like this:

```js
searchPaths: [
  '../../node_modules/@my-company/core/components/atoms',
  '../../node_modules/@my-company/core/components/molecules',
]
```

With this config instead, storybook starts without errors:
```js
searchPaths: [
  path.resolve(__dirname, '../../node_modules/@my-company/core/components/atoms'),
  path.resolve(__dirname, '../../node_modules/@my-company/core/components/molecules')
]
```

But paths doesn't seems to be working at all as some components are not loading, and I am getting this error on my browser console for all of that are using searchPath config:

```
Unexpected error while loading ./components/atoms/button/button.stories.js: Template render error: (path/to/workspace/folder/packages/ds-core/components/atoms/button/template.njk)
  Template render error: (path/to/workspace/folder/packages/ds-core/components/atoms/button/template.njk)
  Error: template not found: icon/macro.njk
```

**Comment by ogonkov** [comment]
Can you please try to use `require.resolve('@my-company/core/components/atoms')` instead?

**Comment by xBau** [comment]
Sure 🙂,

With this config
```
searchPaths: [
  require.resolve('@my-company/core/components/atoms'),
  require.resolve('@my-company/core/components/molecules'),
]
```

I get this error
```
info => Using implicit CSS loaders
ERR! Error: Cannot find module '@adela/core/components/atoms'
```

I will recreate a basic demo so you can test it better.

**Comment by baticodes** [comment]
@ogonkov I have created a basic repo,

https://github.com/baticodes/njk-monorepo

**Comment by ogonkov** [comment]
How to reproduce? Npm i?

**Comment by ogonkov** [comment]
Thank you, will check it out on a weekend

**Comment by baticodes** [comment]
`npm i` on root folder and on storybook folder.

Then, on storybook folder `npm start`.

**Comment by baticodes** [comment]
For anyone with the same issue, this made the trick for me:

```
const packagePath = path.dirname(require.resolve("@my-company/components/package.json"));
...

{
  loader: 'simple-nunjucks-loader',
  options: {
    searchPaths: [
      path.join(packagePath, 'atoms'),
      path.join(packagePath, 'molecules'),
    ]
  }
}
```
