### ISSUE TITLE
Live Reload Available?

### ISSUE THREAD

**Issue by rrdesignweb** [ogonkov/nunjucks-loader#128]
Hi there, wondering if the plugin supports live reload, or any advice how to achieve this? I can only see my changes once I refresh the screen.

This done through devServer or html-webpack-plugin or other?

This is my current setup seems to work fine otherwise - https://github.com/rrdesignweb/webpack-config/blob/main/webpack.config.js using webpack 5

Thanks appreciate your time!

**Comment by rrdesignweb** [comment]
Never mind I had to import my nunjucks into my index.js silly me! feel free to close this

**Comment by ogonkov** [comment]
Related to #111

**Comment by jhancock532** [comment]
As the above link no longer works, [here's the new location of the repository referenced](https://github.com/rrdesignweb/webpack-config-multi-brand/blob/master/webpack.config.js), and [here's the change made to the index file](https://github.com/rrdesignweb/webpack-config-multi-brand/blob/38234ce76f1d2dd3e26cb645ab164a2eecf873d3/src/index.jsx#L12).
