### ISSUE TITLE
Environment Variables Support

### ISSUE THREAD

**Issue by rrichgithubwork** [ogonkov/nunjucks-loader#130]
Hi wondering if it possible to pass in environment variables into templates?

I am using https://github.com/toddbluhm/env-cmd in my project using the .env-cmdrc.json format, 

and have examples where I would like to bring in ENV var e.g
`    <title>{{ ENV_PAGE_TITLE }} - {{ENV_BRAND}}</title>
`
I have tried adding `environment: process.env.NODE_ENV` as an option to HtmlWebPackPlugin with no luck, is there a way to call in to the loader? I saw this issue https://github.com/ogonkov/nunjucks-loader/issues/106 would I create a js file to point the env vars somehow? I am not exactly sure how this would work, if this is the way to do it are you able to give an example?

Thanks

**Comment by rrichgithubwork** [comment]
I have managed to solve it using templateParameters in the htmlwebpackplugin

**Comment by ogonkov** [comment]
Yep, loader just compiles templates. You should pass all required variables in places, where you invoke your compiled template.
