### ISSUE TITLE
How include template into another template

### ISSUE THREAD

**Issue by CallOBock** [ogonkov/nunjucks-loader#155]
**Environment**
Node version: 16.15
simple-nunjucks-loader version: 3.2.0
webpack version: 5.75

**Describe the bug**
I'm trying to include a template in a template, as described here ["include"](https://mozilla.github.io/nunjucks/templating.html#include). But I am getting an error:

`ERROR in ./mypage/test_timetable/src/templates/timetable_row.tpl
Module build failed (from ./node_modules/simple-nunjucks-loader/lib/cjs/loader.js):
Error: Template "./timetable_row/actions.tpl" not found`

I connect like this: `{% include "./timetable_row/actions.tpl" %}` in `timetable_row.tpl`

Folder structure:
![изображение](https://user-images.githubusercontent.com/33382201/203010523-4b0cf03c-7680-4b8e-9f76-4df50dd61133.png)

   
Webpack rule:
`{
                test: /\.(tpl)$/, 
                use: [{
                    loader: 'simple-nunjucks-loader'
                }]
 },`

**Expected behavior**
Part of the template has been successfully connected

**Comment by ogonkov** [comment]
It looks like you use relative paths. Loader support only absolute paths relative to given `searchPaths`.
