### ISSUE TITLE
It's not clear how to load assets via webpack

### ISSUE THREAD

**Issue by ogonkov** [ogonkov/nunjucks-loader#17]
Dig how to properly include `require()` calls to assets

**Comment by ogonkov** [comment]
It's better to inject custom global `static` to `env` and then replace it with `require()` invocation.

This could be supported by PyCharm with Django/jinja2 support, and probably benefit in code completion and etc.

**Comment by quentinneyraud** [comment]
So, i tried something like this

**Structure**

- webpack.config.js
- get-asset.js
- index.html
- assets/
  - img
    - sample.jpg

```js
// webpack.config.js

module.exports = {
  module: {
    rules: [{
      test: /\.(html|njk|nunjucks)$/,
      use: [
        {
          loader: 'simple-nunjucks-loader',
          options: {
            globals: {
              getAsset: path.resolve(__dirname, './get-asset.js')
            }
          }
        }]
    }, {
      test: /\.jpg$/i,
      use: ['file-loader']
    }]
  }
}
```

```js
// get-asset.js

module.exports = assetUrl => require(`./assets/${assetUrl}`)
```

```html
// index.html

<img src="{{ getAsset('img/sample.jpg') }}">
```

But webpack bundles all files in `assets` directory. If i have an other image in `assets/img/sample2.jpg`, it will be bundled even if i don't require it. 

This can be limited to some files by using `require.context`

```js
// get-asset.js

const ctx = require.context('./assets', true, /\.(jpg|png)$/i)
module.exports = assetUrl => ctx(`./${assetUrl}`)
```

so only `.jpg` and `.png` files are bundled, but i still have files that i don't require

**Comment by ogonkov** [comment]
It's should be supported on precompilation level of loader. I will add fake global `static` function, that will wrap first argument to `require(...)`, then i will unquote it to make `webpack` load it as dependency of template.

I haven't implement it yet, i'm afraid.

**Comment by ogonkov** [comment]
I think you can emulate same behaviour by replacing require calls with some other loader, like [`string-replace-loader`](https://www.npmjs.com/package/string-replace-loader) (i haven't test this loader and solution):

**webpack.config.js**

```js
module.exports = {
  module: {
    rules: [{
      test: /\.njk$/,
      use: [
        {
          loader: 'string-replace-loader',
          options: {
            search: '['"]replace_this_require\(([^)])\)['"]',
            replace: (match, p1) => `require(${p1})`,
            flags: 'g'
          }
        },
        {
          loader: 'simple-nunjucks-loader',
          options: {
            globals: {
              static: path.join(__dirname, 'static.js')
            }
          }
        },
      ]
    }]
  }
};
```

**static.js**

```js
module.exports = (r) => `replace_this_require(${JSON.stringify(r)})`
```

**Comment by ogonkov** [comment]
@quentinneyraud i got WIP PR with working assets loading, see above.

**Comment by ogonkov** [comment]
@quentinneyraud i've just pushed assets loading to `master`, can you test does it work for you?

**Comment by quentinneyraud** [comment]
Yes, just saw your comment in my repo. I have tested it and it works great. 

I'm using it for assets when i know their complete path like [here](https://github.com/quentinneyraud/akaru-starter/blob/master/pages/home/index.html)

```
static('./img/sample.jpg')
```
But i kept my `getAsset` function for dynamic assets [here](https://github.com/quentinneyraud/akaru-starter/blob/master/components/blocks/svg/index.html), `static()` for dynamic assets throw an error

```
getAsset('svg/' + props.name + '.svg')
```

**Comment by ogonkov** [comment]
@quentinneyraud can you post this error here?

**Comment by ogonkov** [comment]
@quentinneyraud can you test latest changes in `add_dynamic_assets_test` branch? Does cover your cases?
