### ISSUE TITLE
Add Nunjucks filters to options

### ISSUE THREAD

**Issue by quentinneyraud** [ogonkov/nunjucks-loader#24]
Hi @ogonkov ,

Is there already a way to pass filters to the nunjucks Environment ? 

I can try to work on this so we can set filters in options like this

```js
// webpack.config.js

{
  test: /\.(html|njk|nunjucks)$/,
    use: [
      {
        loader: 'simple-nunjucks-loader',
        options: {
            filters: {
              fromloader: str => `${str} from loader`
            }
        }
      }]
 }
```

```html
<p>{{ 'Hello' | fromloader }}</p>

=> returns <p>Hello from loader</p>
```

**Comment by ogonkov** [comment]
Hello, @quentinneyraud 

Not yet.

I will add filters with same API as [`extensions`](https://github.com/ogonkov/nunjucks-loader#extensions):

```js
module.exports = {
    module: {
        rules: [
            {
                test: /\.njk$/,
                use: [{
                    loader: 'simple-nunjucks-loader',
                    options: {
                        filters: {
                            fromloader: path.join(__dirname, 'from-loader-filter.js')
                        }
                    }
                }]
            }
        ]
    }
};
```

I think i will done it on this week. You can watch a progress for stable [v1 in projects](https://github.com/ogonkov/nunjucks-loader/projects/1).

I'm trying to avoid passing functions in loader, to keep dependencies of each templates tidy.

**Comment by ogonkov** [comment]
If you want, PRs are welcome :)

**Comment by ogonkov** [comment]
@quentinneyraud can you checkout github fix?

You can install latest master by changing version to:

```json
{
  "devDependencies": {
    "simple-nunjucks-loader": "ogonkov/nunjucks-loader#master"
  }
}
```

Feel free to reopen this issue, if your problem not fixed.

**Comment by quentinneyraud** [comment]
Thanks, it works great 👍

**Comment by ogonkov** [comment]
Great

I will publish version to npm soon, found a bug with used extensions duplication.
