### ISSUE TITLE
template not found error in Windows

### ISSUE THREAD

**Issue by navedmirCM** [ogonkov/nunjucks-loader#42]
I am trying to import a nunjuck template(html file). It is imported correctly but the template path inside the object is messed up, half is windows stlye and half is linux.

**browser Console error**

` list.js?986a:17 Error: template not found: \products\_productLoader.html
    at createTemplate (nunjucks-slim.js?cede:1497) 
    at next (nunjucks-slim.js?cede:368) 
    at handle (nunjucks-slim.js?cede:1536) 
    at eval (nunjucks-slim.js?cede:1546) 
    at next (nunjucks-slim.js?cede:366)
 `

**The bundle object :-** 
![logging the object](https://user-images.githubusercontent.com/59809786/73048738-3ca73e80-3ece-11ea-976d-95cc89b23d52.PNG)

**My import statement :-** 
`const _productLoaderHtml = require('../../../views/nunjucks/products/_productLoader.html')`

**Comment by ogonkov** [comment]
Can you make a repo to reproduce an error?

**Comment by navedmir** [comment]
So , I tested again and the issue occurs only in windows. There is a template not found error on windows because the template name doesn't match with nunjucks.render(template). 
It is because of linux vs windows path issue.
Eg :- 

`__nunjucks_module_dependencies__.templates["products/_productLoader.html"]
 nunjucks.render("products\\_productLoader.html")
`

For ref :- 
https://github.com/mozilla/nunjucks/issues/146

**Comment by navedmir** [comment]
Suggested change in file loader.js , line 50

`
 const resourcePathString = JSON.stringify(resourcePathImport.replace(/\\/g, '/'));
`
I am using the same code, which is used in nunjucks to modify the template name 

https://github.com/mozilla/nunjucks/blob/master/nunjucks/src/precompile.js#L113

**Comment by ogonkov** [comment]
What is your template ref looks like in `njk` file?

**Comment by ogonkov** [comment]
I think I need to make sure that path is not changed after precompilation. I will add tests and fix it on this week.

**Comment by ogonkov** [comment]
For history, all tests failed on Windows environment https://travis-ci.org/ogonkov/nunjucks-loader/builds/643552671

**Comment by ogonkov** [comment]
Seems like it is expected behaviour (mozilla/nunjucks#761 & mozilla/nunjucks#825), and i should force unix-style path in loader too.

**Comment by ogonkov** [comment]
@navedmir please test latest master for your project, does it work for you?

You can change version to latest git like

```json
{
  "devDependencies": {
    "simple-nunjucks-loader": "ogonkov/nunjucks-loader#afa716d"
  }
}
```

**Comment by navedmirCM** [comment]
Is there a plan to release this anytime soon? 
Referencing the commit "ogonkov/nunjucks-loader#afa716d"  doesn't work because there is no lib directory as the project is not build.

**Comment by ogonkov** [comment]
@navedmirCM sure, did this patch work for you?

**Comment by ogonkov** [comment]
@navedmirCM sorry, i got your problem. Will release it soon.

**Comment by ogonkov** [comment]
Released in v1.0.1

**Comment by ogonkov** [comment]
@navedmirCM @navedmir please share your experience with latest version

**Comment by navedmirCM** [comment]
It works on windows now, I will test it more with other features.
Thanks
