### ISSUE TITLE
How to get nunjucks-includeData extension working

### ISSUE THREAD

**Issue by danielbaars** [ogonkov/nunjucks-loader#66]
Hello!

Do you perhaps have a suggestion on how I could get the includeData extension (https://github.com/VincentLeung/nunjucks-includeData) working with this loader? I tried to adapt the markdown example but to no avail.

Many thanks beforehand!

**Comment by ogonkov** [comment]
This plugin is not compatible with loader yet. But loader have same functionality built-in

```
{{ set user = static('user.json') }}
```

I can add environment as argument if you really want to use this plugin. But imported JSON would not trigger webpack rebuild when it changes, because loader wouldn't aware of that files.

**Comment by danielbaars** [comment]
Oh wow, that's even better! THANK YOU!

**Comment by ogonkov** [comment]
I'm glad it helped
